apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet19824github
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet19824github 
  name: dotnet19824github
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet19824github 
